---
name: HTML-FormatText-WithLinks
version: 0.08
author:
  - 'Struan Donald. E<lt>struan@cpan.orgE<gt>'
  - 'L<http://www.exo.org.uk/code/>'
  - |-
    Ian Malpass E<lt>ian@indecorous.comE<gt> was responsible for the custom 
    formatting bits and the nudge to release the code.
abstract: HTML to text conversion with links as footnotes
license: perl
requires:
  HTML::FormatText: 0
  HTML::TreeBuilder: 0
  URI::WithBase: 0
build_requires:
  Test::More: 0
provides:
  HTML::FormatText::WithLinks:
    file: lib/HTML/FormatText/WithLinks.pm
    version: 0.08
generated_by: Module::Build version 0.25
